#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2025 Erik Heckman
#
# v0.1.0
#
# Usage: example [options] <argv>...
# Options:
#   --val VAL     Print a value. ## default:'foo '
#                 ## env:EX_VAL conf:VAL
#   --force       Force thing
#                 ## default:'false'
#                 ## true:on false:off env:VERBOSE conf:VERBOSE
#   -a --all      Print all.
#   -n            None
#   --hel.p        Show help options.
#   --ve<rsi>on     Print program version.
#

##  --no-force    Be carefuel with the thing.

# set -x

eval "$(./auto-docopts "$0" -A OPTS : "$@")"

main(){
	declare -p OPTS
	echo "${@@A}"
}

main "$@"
